drop table IF EXISTS users CASCADE;
drop table IF EXISTS categories CASCADE;
drop table IF EXISTS locations CASCADE;
drop table IF EXISTS events CASCADE;
drop table IF EXISTS requests CASCADE;
drop table IF EXISTS compilations CASCADE;
drop table IF EXISTS compilations_events CASCADE;


-- пользователи
create TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(254) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (id),
  CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

-- категории
create TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (id),
  CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

-- места событий
create TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,
  CONSTRAINT pk_location PRIMARY KEY (id)
);

-- события
create TABLE IF NOT EXISTS events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  annotation VARCHAR(2000) NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON delete CASCADE,
  created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  description VARCHAR(7000) NOT NULL,
  event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  initiator_id BIGINT REFERENCES users(id) ON delete CASCADE,
  location_id BIGINT REFERENCES locations(id) ON delete CASCADE,
  paid BOOLEAN DEFAULT FALSE,
  participant_limit INT DEFAULT 0,
  published_on TIMESTAMP,
  request_moderation BOOLEAN DEFAULT TRUE,
  state VARCHAR(255) NOT NULL,
  title VARCHAR(120) NOT NULL,
  CONSTRAINT pk_event PRIMARY KEY (id)
);

-- заявки на участие в событиях
create TABLE IF NOT EXISTS requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created TIMESTAMP NOT NULL,
  event_id BIGINT REFERENCES events(id) ON delete CASCADE,
  requester_id BIGINT REFERENCES users(id) ON delete CASCADE,
  status VARCHAR NOT NULL,
  CONSTRAINT pk_request PRIMARY KEY (id)
);

-- подборки событий
create TABLE IF NOT EXISTS compilations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pinned BOOLEAN,
  title VARCHAR NOT NULL,
  CONSTRAINT compilation PRIMARY KEY (id)
);

-- подборки событий с событиями
create TABLE IF NOT EXISTS compilations_events (
  event_id BIGINT REFERENCES events(id) ON delete CASCADE,
  compilation_id BIGINT REFERENCES compilations(id) ON delete CASCADE,
  PRIMARY KEY (event_id, compilation_id)
);